site_name: EITS Docs
site_url: https://koala.soupup.online

# Project information
repo_url: http://gitlab.soupup.online/soupup/koala
repo_name: soupup/koala


site_dir: build/public
docs_dir: docs

theme:
  icon:
    repo: fontawesome/brands/git-alt
    nnotation: material/plus-circle-outline

  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - md_in_html              # Annotation
  - footnotes
  - admonition
  - footnotes
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:      # Checkbox
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # This is not an error
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/mathjax/tex-mml-chtml.js

# extra_css:
#   - assets/xterm/xterm.css
#   - assets/terminal.css
#   # - assets/extra.css
#   - assets/koala-lexer.css

# nav:
#   - Home: index.md

#   - Syntax:
#       - Intro: Syntax/Intuition.md
#       - Index: Syntax/index.md

#   - Tools:
#       - draft: Tools/draft.md
#       - Index: Tools/index.md

#   - REPL: REPL.md
